# Generated by Django 2.0 on 2017-12-26 20:38

import ckeditor.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('created_date', models.DateField(default=datetime.date.today)),
                ('body', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
